### ISSUE TITLE
Record playwright tests in parallel

### ISSUE THREAD

**Issue by jasonLaster** [Replayio/replay-cli#9]
At the moment we have to tell playwright to record tests synchronously. We should be able to record multiple tests in parallel.

**Comment by ryanjduffy** [comment]
I've tried to use support for `RECORD_REPLAY_METADATA` to support this since the original blocker was running the tests serially on one worker so we (mostly) knew the latest recording was for the last test. I've since discovered that the browser instance is reused for all tests on a given work worker and that the environment variables are only picked up on first launch as you might expect. 

There's been some discussion around [spawning a new browser per test](https://github.com/microsoft/playwright/issues/8981) but it seems to be an open question. Ideally, I'd prefer to reuse the instance but we need some other way to fetch the latest env variables.

One idea is to add yet another env variable that points to a file that contains metadata (e.g. `RECORD_REPLAY_METADATA_FILE`). Presumably, we should be able to define a unique location per-worker and then set test-related metadata into that file which then could be read by the driver.

Going to ask in the playwright slack for advice before starting engineering work on this.

cc: @bhackett1024 on feedback or other ideas

**Comment by ryanjduffy** [comment]
Tracking https://github.com/microsoft/playwright/issues/13362 which might help us in the long term but isn't an immediate solution.

**Comment by ryanjduffy** [comment]
I went ahead with a proof of concept for the approach described above. I think that it it'll work for us but we'll see how everyone feels about it. The good news is that I think it'll scale to the other test runners since there isn't much unique to playwright. 🤞 

- [ ] https://github.com/Replayio/replay-cli/pull/16
- [ ] https://github.com/RecordReplay/backend/pull/5265

**Comment by ryanjduffy** [comment]
🤞 this should be working with `@replayio/playwright@0.3.0` and the GH Action `replayio/action-playwright@v0.3.1`
